### ISSUE TITLE
Folders in storage buckets are disappearing

### ISSUE THREAD

**Issue by libovness** [supabase/storage-api#10]
# Bug report

## Describe the bug
Folders in storage buckets are disappearing

## To Reproduce
1. Go to Storage tab
2. Create a bucket
3. Create a sub-folder
4. Refresh page
5. *Sub-folder has disappeared*

## Expected behavior
Sub-folder would still be there

## System information

- OS: macOS
- Browser: Chrome

**Comment by thebengeu** [comment]
Hi @libovness, the fix for this issue will be deployed in about a week.

**Comment by inian** [comment]
This has been now deployed to prod @libovness
