### ISSUE TITLE
Fix extension function

### ISSUE THREAD

**Issue by inian** [supabase/storage-api#12]
Right now the `extension` function [returns the second part](https://github.com/supabase/storage-api/blob/514899eb2d0f1823abc95d497f2e801978cc49ff/src/test/db/02-storage-schema.sql#L74) of the filename after splitting by `.`. 

Instead the last part should be returned so that the extension for the file `cat.meme.jpg` is returned as `jpg` and not as `meme`.

**Comment by YashKandalkar** [comment]
@inian Hello! 
I wanted to fix this, I didn't knew a lot about psql functions but from what I searched, this works:
```sql
return (select regexp_replace('cat.meme.jpg', '^.*\.', ''));
```
(or making a `_extension` var and returning that)

I have only tested this in a sql editor, not inside this repo, as you need to have an aws s3 instance to develop (right?)
I tried running `npm test` only after renaming `.env.sample` to `.env`, same with .env.test but got 
```
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
```
are there any dependencies need to be installed?

**Comment by inian** [comment]
Hey Yash, 

Yup something like that regex should work. You will need a AWS S3 bucket and AWS credentials setup. I have updated the README recently. Let me know if something is not clear from that. 

Can you try again by renaming `.env.test.sample` to `.env.test` also?

**Comment by bariqhibat** [comment]
Hey @inian, is this issue resolved already by @YashKandalkar? If not, can I give it a shot?

**Comment by inian** [comment]
Go ahead @bariqhibat! I haven't tested @YashKandalkar's solution, so even if you can help test it out, it will help.

**Comment by bariqhibat** [comment]
> Go ahead @bariqhibat! I haven't tested @YashKandalkar's solution, so even if you can help test it out, it will help.

I do a little bit of research on this, and found this to be a good solution
```sql
return reverse(split_part(reverse(_filename), '.', 1))
```
