### ISSUE TITLE
Allow generate upload URL

### ISSUE THREAD

**Issue by riderx** [supabase/storage-api#131]
# Feature request

in my soft https://capgo.app i have made a CLI tool to allow users to upload version to the tool.
To connect to the account in the cli i have created apikey and Netlify cloud function, for upload the CLI, it send to the cloud function and then to supabase.
So a good solution could be allow retrieve upload url as download url to send it from my cloud function to the cli and upload direct from the client.
i have try to upload to supabase function but i hit the payload limit.

**Comment by alaister** [comment]
Hey @riderx,

Do you think it would be possible to close this in favour of #81? Is there anything you require that isn't covered by that issue?

**Comment by riderx** [comment]
Oh, I missed it! This is precisely what i need!
