### ISSUE TITLE
File integrity

### ISSUE THREAD

**Issue by philanton** [supabase/storage-api#140]
# Bug report

## Describe the bug

After uploading/downloading file's size and content doesn't remain the same.

## To Reproduce

Lets assume that bucket is already created, then the next steps are:

![DeepinScreenshot_select-area_20220421123106](https://user-images.githubusercontent.com/66011711/164425724-fa602b7e-a749-4067-91d3-7466ce9aa585.png)

So from the image you can see that original image's size was 131K and downloaded image's size became 84K.

## Expected behavior

I want to ensure file integrity, and at least return error if something goes wrong.

## System information

Storage is running as pod on K8s cluster and uses image built from [this fork](https://github.com/openware/storage-api).
On client-side: curl 7.82.0 (x86_64-pc-linux-gnu)

## Additional context

FYI, there are sometimes also some unpredictable failures with:
* migrations, like "path_tokens" column doesn't exist, but I didn't see anything in the logs about this, so I had to look for causes and solutions in the source code.
* S3 bucket, I've already seen issue here about credentials, that is important, but it is not just that. Sometimes I see the errors like below, that are not comprehensible for the end user. For that case as S3 bucket I used GCP storage, and in general it worked, but this log was printed after I tried to delete assets.
Logged error: 
```
{"level":"info","time":"2022-04-21T08:50:44.932Z","pid":23,"hostname":"storage-0","reqId":"req-9","req":{"method":"DELETE","url":"/object/logos","hostname":"storage:5000","remoteAddress":"10.233.118.159","remotePort":46064},"msg":"incoming request"}
{"level":"error","time":"2022-04-21T08:50:45.031Z","pid":23,"hostname":"storage-0","reqId":"req-9","tenantId":"odax_studio_admin","req":{"method":"DELETE","url":"/object/logos","hostname":"storage:5000","remoteAddress":"10.233.118.159","remotePort":46064},"res":{"statusCode":500},"err":{"type":"S3ServiceException","message":"Invalid argument.","stack":"InvalidArgument: Invalid argument.\n    at deserializeAws_restXmlDeleteObjectsCommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5246:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at /app/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\n    at /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20\n    at StandardRetryStrategy.retry (/app/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\n    at /app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20\n    at /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22","name":"InvalidArgument","$fault":"client","$metadata":{"httpStatusCode":400,"attempts":1,"totalRetryDelay":0},"Code":"InvalidArgument","Details":"Cannot create buckets using a POST."},"msg":"Invalid argument."}
{"level":"info","time":"2022-04-21T08:50:45.033Z","pid":23,"hostname":"storage-0","reqId":"req-9","tenantId":"odax_studio_admin","res":{"statusCode":500},"responseTime":100.86035537719727,"msg":"request completed"}
```

**Comment by thebengeu** [comment]
That's odd, from https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html: "Amazon S3 never adds partial objects; if you receive a success response, Amazon S3 added the entire object to the bucket."

Is there any way to duplicate this issue? If it's random, how often does it occur?

**Comment by philanton** [comment]
Hello @thebengeu, I've tested few times, but integrity issue wasn't due to S3, after I switched back to `file` issue was reproduced the same way

**Comment by darora** [comment]
@philanton this service is extensively used and we haven't had any reports of this. I can't reproduce this in a quick spot check just now either.

Based on a quick glance, I'd say your usage of the `-d` flag for your curl upload is likely the source of the issue. Please use the `--data-binary` flag instead and let us know if you're still able to reproduce the issue.
