### ISSUE TITLE
Make object upload size limit configurable

### ISSUE THREAD

**Issue by inian** [supabase/storage-api#16]
Right now, this is configured on server startup and is set to 50 MB on the Supabase hosted platform. We will need a way to expose this to users.

**Comment by alanbar** [comment]
It would be nice to restrict files to a certain size for conformity on reports etc
Or is there software available to do this in the browser?

**Comment by inian** [comment]
You can do this in the browser via JavaScript @alanbar. [Here](https://stackoverflow.com/questions/3717793/javascript-file-upload-size-validation) are a few ways in which you can do it.

**Comment by heauton** [comment]
Just to be clear, when using js library https://supabase.io/docs/guides/storage#upload-a-file
I can't upload more than 50mb. Is this correct? Is there a workaround to increase upload size for now? @inian

**Comment by inian** [comment]
Hi @heauton, 
> I can't upload more than 50mb. 

yup thats right

> Is there a workaround to increase upload size for now

Reach out to beta@supabase.io if you want to increase it for your project. If you are self hosting, change [this value](https://github.com/supabase/storage-api/blob/74d8d6388511aa2abaecb39601b898df21d9fd90/.env.sample#L10) and restart the server. 

I am keeping this issue open to track doing this from the dashboard

**Comment by thebengeu** [comment]
Resolved with supabase/supabase#5597, #75 and #76.

**Comment by MMTE** [comment]
I'm investigating this option on **self-hosted versions**? how could we change environment a  max file size of e.g 500 MB?

**Comment by kutovoy** [comment]
i have same issue "Failed to upload fire_alarm.mov: The object exceeded the maximum allowed size", changing "FILE_SIZE_LIMIT" to let's say 1073741824 and restarting docker compose doesn't help

**Comment by MMTE** [comment]
> i have same issue "Failed to upload fire_alarm.mov
 @kutovoy 
 mine got fixed. I had a lot of database unhealthy messages. I sort of cleaned all containers and volumes and just backed up my migrations and then started again. I wrote the limit in this format `file_size_limit = "5000MiB"`
finally I uploaded a large file successfully.

**Comment by kutovoy** [comment]
thanks MMTE! I did few more attempts and figured out that I had to edit the docker-compose.yml file instead of editing docker/.env since the ENV var had to be passed into the storage container. So the correct setting in the docker-compose.yml (for local docker installation) is services.storage.environment.FILE_SIZE_LIMIT and it's finally working for me

**Comment by MMTE** [comment]
> thanks MMTE! I did few more attempts 

Glad to hear.
