### ISSUE TITLE
Batch upload & download

### ISSUE THREAD

**Issue by KolbySisk** [supabase/storage-api#166]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm building an app where users upload images, and then the images are rendered on a page in a grid. Think Instagram. Right now it's very slow as there is no way to upload and download in batch. Instead, when downloading, I have to get bucket list, and make a new request to download for each.

## Describe the solution you'd like

1. Download array of files
`const { data, error } = await supabase.storage.from('photos').download(['photo1.png', 'photo2.png'])`

2. Download all files in bucket
`const { data, error } = await supabase.storage .getBucket('photos/${userId}')`

## Describe alternatives you've considered

Living with the performance hit, or using S3 directly.

**Comment by KolbySisk** [comment]
I see, that makes sense. I normally don't download files in this way. When I've used S3 in the past I was able to access images by url - is that a possibility?

**Comment by inian** [comment]
Yup you can create [a signed url](https://supabase.com/docs/reference/dart/storage-from-createsignedurl) for private buckets or a [public url](https://supabase.com/docs/reference/dart/storage-from-getpublicurl) for public buckets if you just want to access assets via a url

**Comment by KolbySisk** [comment]
Pays to read the docs 😅

Thanks for your help
