### ISSUE TITLE
Allow customizing `content-type` when file is`text/html`

### ISSUE THREAD

**Issue by qiushiyan** [supabase/storage-api#186]
This [line](https://github.com/supabase/storage-api/blob/3cd3c912819b4cfe1f05fd9d8bc1a68a8fd800c8/src/utils/index.ts#L85) forces the response content type to be `text/plain` when the object is of type `text/html`. It would be nice to have a customizable option. My use case with storage is storing some user-generated html files, and this blocks me from getting the actual rendered page but the html source code.

**Comment by inian** [comment]
Hey @qiushiyan are you self hosting storage-api and want this to be configurable?

**Comment by mattaylor** [comment]
Please can you explain why you are rewriting the content-type `text/plain` when the file is `text/html`. This is super annoying as it means I cant host html files eg for openapi docs using the storage api. Is there anyway to override this behaviour?

**Comment by mattaylor** [comment]
I actually found a workaround for this but it is still annoying.
