### ISSUE TITLE
Browser never use cache when requesting image from storage

### ISSUE THREAD

**Issue by ikhsan** [supabase/storage-api#193]
# Bug report

## Describe the bug

The public url from storage responds with etag and last modified headers. The problem is that subsequent calls will never get 304 response, as if it ignores the etag and the last modified headers.

## To Reproduce

**1st call**

```bash
# request
curl -v --request GET \
  --url https://rntpzayauzmhsmxjjtfz.supabase.co/storage/v1/object/public/images/test-box-image.jpeg \
  1> /dev/null

# response
< HTTP/2 200 
< cache-control: max-age=3600
< etag: "76d19e08653c1055af52af039af2b6ce"
< last-modified: Mon Sep 19 2022 07:06:41 GMT+0000 (Coordinated Universal Time)
# ...other headers
```

**2nd call (or subsequent calls)**

```bash
# request
curl -v --request GET \
  --url https://rntpzayauzmhsmxjjtfz.supabase.co/storage/v1/object/public/images/test-box-image.jpeg \
  --header 'if-modified-since: Mon Sep 19 2022 07:06:41 GMT+0000 (Coordinated Universal Time)' \
  --header 'if-none-match: "76d19e08653c1055af52af039af2b6ce"' \
  1> /dev/null

# response
< HTTP/2 200 
< cache-control: max-age=3600
< etag: "76d19e08653c1055af52af039af2b6ce"
< last-modified: Mon Sep 19 2022 07:06:41 GMT+0000 (Coordinated Universal Time)
# ...other headers
```
## Expected behavior

Subsequent calls from client with etag and last modified header should return 304.

## Screenshots

Refreshing images in Firefox (tested with curl and Chrome too) always gives 200, never 304. 

See how there are 3 requests and all returns 200. The 2nd and the 3rd requests have matching etag and last modified, so it should return 304 instead.

![Screenshot 2022-09-19 at 08 23 47](https://user-images.githubusercontent.com/781254/190968303-e6ecfe40-9ce5-4511-af3f-cda7e64e40af.png)

## System information

- OS: [macOS]
- Browser[chrome, firefox]

**Comment by inian** [comment]
Hi @ikhsan, I can confirm that your PR fixes the issue. The fix should be deployed to prod in a day or two.

**Comment by ikhsan** [comment]
Awesome, I'll test again in 2 days 👍  

Hopefully, this prevents your customers (including me!) from overcharging storage egress

**Comment by inian** [comment]
Hi @ikhsan this fix has been deployed to prod now. Thanks for reporting and the PR!

**Comment by ikhsan** [comment]
Glad that it works! Hopefully, this will make the storage egress calculation fairer 👍
