### ISSUE TITLE
Storage list sort order

### ISSUE THREAD

**Issue by saltcod** [supabase/storage-api#196]
Sequential numerical filenames don't sort properly. 

In Storage, if we have if we have 1.png, 10.png, 11.png, ..., 2.png, 20.png, 21.png, 
In Finder on Mac, these items would be sorted: 1.png, 2.png, 3.png, ... 10.png, 11.png, etc.

**Storage on top, Finder on bottom:** 

<img width="329" alt="CleanShot 2022-08-24 at 16 16 23@2x" src="https://user-images.githubusercontent.com/105593/186498692-c852fd92-c725-4422-ad58-dc4e5ef54699.png">

**Comment by fenos** [comment]
This is expected, as the ORDER BY clause on a string in Postgres does not take into account the number cardinality, I would recommend sorting by `created_at`.

Alternatively, if the formatted order is important you can always create an RPC function that will allow you to normalize the string and sort by the numeric value

for example:

```
SELECT *
FROM   objects
ORDER  BY split_part(name, '.', 1)::numeric;
```
