### ISSUE TITLE
Support upsert functionality 

### ISSUE THREAD

**Issue by inian** [supabase/storage-api#21]
More info - https://github.com/supabase/storage-js/issues/7

**Comment by ankitjena** [comment]
@inian Is this issue being worked on or can I take it up?

**Comment by inian** [comment]
Go for it @ankitjena! Let me know if there are any issues in getting started.

**Comment by ankitjena** [comment]
Hey @inian , the readme says to only set `GLOBAL_S3_BUCKET` and `REGION`, in the `.env` and set up the aws config. What about the other fields in the `.env` field?
- The `ANON_KEY`, `SERVICE_KEY`, `PROJECT_REF`  are we supposed to use those from project created in supabase
- Also how do I test it using and api client, looking at the code I think an authorization header was required

Thanks

**Comment by inian** [comment]
Hi @ankitjena, you don't need to change any other variables in the .env file. This sets up a full local environment and apart from a S3 bucket, you don't need anything external like a Supabase Project to begin development. 

I have updated the README to add some instructions on local testing and the API docs are [here](https://supabase.github.io/storage-api/#/). Can you pull from master and give it a shot?

**Comment by ankitjena** [comment]
@inian The create bucket and get buckets API works, I was trying to create an object and it returns this error to me
```
{
  "statusCode": "42501",
  "error": "",
  "message": "new row violates row-level security policy for table \"objects\""
}
```
Something I am doing wrong here?

**Comment by inian** [comment]
You will need to add RLS policies to get around this permission issues Ankit. For local dev, you can use [the service key](https://github.com/supabase/storage-api/blob/90af22f9238dd380651d58fbe19ec0906638fd37/.env.sample#L2) instead which bypasses RLS

**Comment by ankitjena** [comment]
That worked. Thanks. I will work on the issue for now.

**Comment by ankitjena** [comment]
@inian Created a PR

**Comment by andrashann** [comment]
@inian can you explain what row-level policies I should add (presumably to the "Other policies under storage.objects" section)? I want the following simple rule actually work for insert/update/delete on the frontend (so no service key), but I get the same error as @ankitjena when I use `upsert: true`

```sql
(
  (bucket_id = 'test-bucket':: text)
  AND ((uid()):: text = (storage.foldername(name)) [ 1 ])
)
```
