### ISSUE TITLE
Seed Storage Files

### ISSUE THREAD

**Issue by 413n** [supabase/storage-api#214]
# Feature request

## Is your feature request related to a problem? Please describe.

I have some static images that I need in every environment. I would like to have them in the `storage`, but at the moment I have to insert them manually one by one using the `storage-js` client.

## Describe the solution you'd like

Is there a way to seed files/images inside the storage without the `storage-js` client? So that I could eventually use that also in the CI/CD?

## Describe alternatives you've considered

Tried creating an Edge function but that is definitely not the scope of them.
I'm open to any suggestion.

## Additional context

Was partially asked here but left without a complete response: https://github.com/supabase/supabase/discussions/7430

**Comment by fenos** [comment]
@413n hello,

In order for me to give you more information I would need to understand more in-depth the way you are provisioning environments and if you are using the self-hosted version of storage-api and which backend driver (s3 / file)

Although, at the first glance I don't see the problem of having a script that uses storage-js to upload files as a seeder.
Could you explain the limitation that you are hitting with this approach?

**Comment by 413n** [comment]
@fenos Hey there, sorry for the big delay here.
I will try your solution and see if it fits the thing I'm looking for.
Feel free to close this. Eventually I will reopen it.
Thanks!

**Comment by fenos** [comment]
Awesome, feel free to re-open with more info
