### ISSUE TITLE
Return ID of storage object in createObject success response

### ISSUE THREAD

**Issue by CrowhopTech** [supabase/storage-api#249]
# Feature request

## Is your feature request related to a problem? Please describe.
I have some cases where I'm maintaining metadata in another table about entries in the Storage table. I'd like to link this by UUID as this stays constant rather than by filename. However, the `createObject` API only returns the path of the uploaded object, not the UUID.

## Describe the solution you'd like
The `createObject` `successResponseSchema` [here](https://github.com/supabase/storage-api/blob/196d5b8696ffda719353eb0e99feb85793eb7522/src/http/routes/object/createObject.ts#L13-L22) should also include an `id: string` field, populated with the UUID of the newly created object row.

## Describe alternatives you've considered

At the moment, I fetch the ID of the newly created object with a second API call, listing the object by name. This works, but is inefficient.

## Additional context

N/A

**Comment by inian** [comment]
fixed in https://github.com/supabase/storage-api/pull/197
