### ISSUE TITLE
Migrations failing to run

### ISSUE THREAD

**Issue by heromiyo** [supabase/storage-api#25]
# Bug report

## Describe the bug

Migrations are failing to run when starting the storage server 

> supa-storage@0.0.1 restart:db
> docker-compose --project-dir . -f src/test/db/docker-compose.yml down && docker-compose --project-dir . -f src/test/db/docker-compose.yml up -d && sleep 5 && npm run migration:run

Stopping storage-api_rest_1 ... done
Stopping storage-api_db_1   ... done
Removing storage-api_rest_1 ... done
Removing storage-api_db_1   ... done
Removing network storage-api_default
Creating network "storage-api_default" with the default driver
Creating storage-api_db_1 ... done
Creating storage-api_rest_1 ... done

> supa-storage@0.0.1 migration:run
> ts-node-dev ./src/scripts/migrate-call.ts

[INFO] 17:56:58 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.3)
running migrations
(node:2616) UnhandledPromiseRejectionWarning: Error: Migration failed. Reason: An error occurred running 'create-migrations-table'. Rolled back this migration. No further migrations were run. Reason: no schema
has been selected to create in
    at D:\PROJECTS\storage-api\node_modules\postgres-migrations\dist\migrate.js:63:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at D:\PROJECTS\storage-api\node_modules\postgres-migrations\dist\with-lock.js:25:28
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not han
dled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
 id: 1)
(node:2616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. clone supabase/storage-api
2. cd storage-api 
3. npm run restart:db
4  migrations failing to run

## Expected behavior

Server should run

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by inian** [comment]
Hi @heromiyo, this happens if you don't have the search path set correctly. Can you ensure that the .env.sample file has been copied to .env and there is a PGOPTIONS [in your .env file](https://github.com/supabase/storage-api/blob/8a08d3a0f27434877b49978b12d7996d1a97c9df/.env.sample#L9)?

**Comment by difelice** [comment]
I'm having similar issue running a container from `supabase/storage-api`, migrations worked fine, and `PGOPTIONS` is in the final `env` list, but for some reason it's still requesting on the `public` schema:

Docker Compose logs:
```sh
torage_1  | running migrations
storage_1  | finished migrations
storage_1  | [1623760631182] INFO (8 on 66b95fdc2426): Server listening at http://0.0.0.0:5000
storage_1  | Server listening at http://0.0.0.0:5000
```

```sh
storage_1   |       "hint": null,
storage_1   |       "details": null,
storage_1   |       "code": "42P01",
storage_1   |       "message": "relation \"public.buckets\" does not exist"
storage_1   |     }
```

```sh
$ docker compose exec storage /bin/bash -c 'env | grep PGO'
PGOPTIONS=-c search_path=storage
```

Thanks.

**Comment by inian** [comment]
Hi @difelice, can you check if postgrest has storage in `PGRST_DB_SCHEMA` like [here](https://github.com/supabase/storage-api/blob/8a08d3a0f27434877b49978b12d7996d1a97c9df/src/test/db/docker-compose.yml#L11)

**Comment by difelice** [comment]
> Hi @difelice, can you check if postgrest has storage in PGRST_DB_SCHEMA like here
Thank you! That was it. I missed completely from the `supabase` PR. 🤗

**Comment by inian** [comment]
Glad its sorted :)
