### ISSUE TITLE
add option to set s3ForcePathStyle or forcePathStyle

### ISSUE THREAD

**Issue by mingfang** [supabase/storage-api#252]
I'm trying to use Storage with S3 compatible services such as Minio and LocalStack.  For that to work I will to set the S3 endpoint and s3ForcePathStyle/forcePathStyle = true.

I'm able to set the endpoint using the GLOBAL_S3_ENDPOINT env.
But there is not way to set s3ForcePathStyle/forcePathStyle.

https://github.com/supabase/storage-api/blob/196d5b8696ffda719353eb0e99feb85793eb7522/src/storage/backend/s3.ts#L43

Please add optional env variable to set s3ForcePathStyle/forcePathStyle =true.

note:
s3ForcePathStyle for aws sdk v2
forcePathStyle for aws sdk v3

**Comment by fenos** [comment]
Hello @mingfang would you be able to raise a PR?

**Comment by mingfang** [comment]
Hi @fenos. I submitted the PR.
