### ISSUE TITLE
Problem trying to download a file larger than 2.4G

### ISSUE THREAD

**Issue by rgarciade** [supabase/storage-api#255]
Hello, I am using the self hosting option in node 16.13.1 and Express 4.17.15

When I try to download a large file it returns the following error

![imagen](https://user-images.githubusercontent.com/10086855/210220714-4cd02bf0-1023-4b86-9343-e84f65b13e0f.png)

It seems that it is an error when trying to open large files in this metod

![imagen](https://user-images.githubusercontent.com/10086855/210221005-99274c07-1604-48d6-bd27-349b713fc3d4.png)

In my local, I had the same error when trying to access a file in the same way.

I got it to work for me in the following way.
![imagen](https://user-images.githubusercontent.com/10086855/210221799-88cbbd8c-2836-4185-8552-673ecd70195c.png)

Maybe you could implement a method that returns a ReadStream like fileInAnotherLocation, so you can return it with the res of express

- OS: Linux ubuntu 22.04
- Version of supabase-js: 2.2.2
- Nodejs 16.13.1
- Express 4.17.15

**Comment by fenos** [comment]
Hello @rgarciade 

Yes, we should implement a stream-based reader for file system storage. 
We currently support streaming for the S3 adapter
