### ISSUE TITLE
`storage.can_insert_object` shows up in my db diff, but I don't think it should

### ISSUE THREAD

**Issue by Taytay** [supabase/storage-api#294]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm developing locally, and I run `supabase db reset`, and then `supabase db remote commit`. [This is the sql I've got in my initial schema, but I don't _think_ it matters](https://raw.githubusercontent.com/motifland/markprompt/1e2d17e54fc6ace8e896287a496d5fc6a92c88ae/config/schema.sql).

The following migration gets created (`20230402131822_remote_commit.sql`):
```sql
set check_function_bodies = off;

CREATE OR REPLACE FUNCTION storage.can_insert_object(bucketid text, name text, owner uuid, metadata jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  INSERT INTO "storage"."objects" ("bucket_id", "name", "owner", "metadata") VALUES (bucketid, name, owner, metadata);
  -- hack to rollback the successful insert
  RAISE sqlstate 'PT200' using
  message = 'ROLLBACK',
  detail = 'rollback successful insert';
END
$function$
;
```

That appears to be an internal function. Not one I added or changed. [Others are getting this too](https://github.com/search?q=CREATE+OR+REPLACE+FUNCTION+storage.can_insert_object&type=code). 

## To Reproduce:

```bash
$ supabase db reset
$  supabase db remote commit
```

## Expected behavior

No diff created if I didn't change that function locally.

## System information

- Windows WSL
- Version of supabase-js: 1.46.5
- Version of Node.js: v16.13.2

**Comment by fenos** [comment]
I think is because the cli is pulling a previous version of storage api, we will update it to the lastest
