### ISSUE TITLE
createSignedUrls returns different URLs for the local environment and production

### ISSUE THREAD

**Issue by yukiyamazaki** [supabase/storage-api#300]
# Bug report

## To Reproduce
supabase flutterでstorageのcreateSignedUrlsを使っています。
しかし、環境によって返ってくるパスが違う可能性があります。

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use createSignedUrls
2. Get signedUrl path in values
3. In the local case, storage.url (http://) is attached, but in the production environment, it is not attached, so you may need to set storage.url yourself.

## System information
- Version of   supabase_flutte: [1.6.2]

**Comment by inian** [comment]
Are you using flutter both locally and in production?

**Comment by yukiyamazaki** [comment]
@inian 
Yes, I am!
