### ISSUE TITLE
Wrong URL generated for resumable upload in storage API for local development 

### ISSUE THREAD

**Issue by dishwad** [supabase/storage-api#339]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Resumable uploads aren't working during local development because the wrong URL is being generated.

## To Reproduce

[Javascript code snippet from Discord thread](https://discord.com/channels/839993398554656828/1111460646131875892/1111460646131875892)

Python code snippet:
```python
from typing import BinaryIO

from tusclient import client

from app.core.config import settings
from app.schemas.token import TokenData

# Must be set to 6MB (for now) according to Supabase's limitations.
DEFAULT_CHUNK_SIZE: int = 6 * 1024 * 1024

def upload_file_to_bucket(
    user_token_data: TokenData, file_name: str, file: BinaryIO, content_type: str = "application/pdf"
):
    endpoint = f"{settings.SUPABASE_URL}/storage/v1/upload/resumable"
    headers = {
        "Authorization": f"Bearer {user_token_data.access_token}",
        "X-Upsert": "true",
    }
    metadata = {
        "bucketName": settings.SUPABASE_DOCUMENT_FILES_BUCKET_NAME,
        "objectName": f"{user_token_data.user_id}/{file_name}",
        "contentType": content_type,
        "cacheControl": "3600",
    }

    tus_client = client.TusClient(endpoint, headers=headers)
    uploader = tus_client.uploader(file_stream=file, metadata=metadata, chunk_size=DEFAULT_CHUNK_SIZE)
    uploader.upload()
```
This exception is generated when the `upload_file_to_bucket` function runs:
```
tusclient.exceptions.TusUploadFailed: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /upload/resumable/ZG9jdW1lbnQtZmlsZXMvYTc0ZGVlZTAtNThhNS00M2QwLTliNzYtODRjYjZkN2MyMDNjL0Jhc2ljLU5vbi1EaXNjbG9zdXJlLUFncmVlbWVudC5wZGYvZjYyNGJiNmYtZWM5YS00MWExLWI4M2QtMDVkMDgxNDI0ZDhl (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1703e61c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

## Expected behavior

Should generate `http://localhost/storage/v1/upload` instead of `http://localhost/upload`.

## Screenshots

[Screenshot in Discord thread.](https://discord.com/channels/839993398554656828/1111460646131875892/1111460646131875892)

## System information

- OS: macOS
- Supabase CLI version: 1.64.8

**Comment by inian** [comment]
Hi Alex, 

Thank you for reporting this issue. 

It was just [fixed](https://github.com/supabase/cli/pull/1186) in the [beta version of the CLI](https://github.com/supabase/cli#install-the-cli). 

It should reach our mainline on June 13th.

**Comment by glib-0** [comment]
I'm still getting this issue with self-hosted Supabase. The first chunk uploads fine, but then subsequent `PATCH`/`HEAD` requests are using `http://localhost/upload/resumable/[fingerprint]` as the uploadUrl - the same value is stored in localStorage. If I change the uploadUrl to `http://localhost:8000/stoarge/v1/upload/resumable/[fingerprint]` then it manages to complete.
