### ISSUE TITLE
supabase-storage exited with code 139 - on ARM  aarch64 CPU machines (solved needs PR)

### ISSUE THREAD

**Issue by Anj-interactivated** [supabase/storage-api#351]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Following the supabase setup with docker compose https://supabase.com/docs/guides/self-hosting/docker#running-supabase

The whole setup runs fine on a laptop but when running on a server I get this:

```supabase-imgproxy               | INFO    [2023-07-06T14:49:39Z] Completed in 107.761µs /health  request_id=SQaajL0LOu73vkp_y4GJd method=GET status=200 client_ip=127.0.0.1
supabase-storage                | running migrations
supabase-storage                | (node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
supabase-storage                | 
supabase-storage                | Please migrate your code to use AWS SDK for JavaScript (v3).
supabase-storage                | For more information, check the migration guide at https://a.co/7PzMCcy
supabase-storage                | (Use `node --trace-warnings ...` to show where the warning was created)
supabase-storage                | finished migrations
supabase-storage exited with code 139
```

when running `docker compose up` with default

`STORAGE_BACKEND: file`

everything is fine, problem appears when changing it to 

```
STORAGE_BACKEND: s3

....rest of the s3 setup is provided and validated to work (on laptop)
```

Hosting is on hetzner with CPU ARM Neoverse-N1 aarch64, Ubuntu 22.04.2 LTS, docker 24.0.2, build cb74dfc, has the issue 

tested with same exact setup of Ubuntu OS and docker ver on laptop runs fine , laptop with Mac os also fine

## To Reproduce

1. get a machine with CPU Architecture aarch64

example:
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               ARM
  Model name:            Neoverse-N1
    Model:               1
    Thread(s) per core:  1
    Core(s) per cluster: 8
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r3p1
    BogoMIPS:            50.00
    Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs

2. follow the instructions https://supabase.com/docs/guides/self-hosting/docker#running-supabase
3. change storage  to use s3 `STORAGE_BACKEND: s3` (provide all related config)

Please note that this issue exists only when using docker compose not when running just storage-api

## Expected behaviour 

storage container runs ok with docker compose

## System information

- Version of Node.js: 18.16.1

## Additional context

issue can be solved by updating the aws libraries 

this has been sloved by updating the aws libraries to the following 
```
    "@aws-sdk/client-s3": "3.369.0",
    "@aws-sdk/lib-storage": "3.369.0",
    "@aws-sdk/node-http-handler": "3.369.0",
    "@aws-sdk/s3-request-presigner": "3.369.0",
```
Looks like it was related to the processor architecture 
```
lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               ARM
  Model name:            Neoverse-N1
    Model:               1
    Thread(s) per core:  1
    Core(s) per cluster: 8
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r3p1
    BogoMIPS:            50.00
    Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
...
```

Then I had to build storage image and use it in the docker-compose.yaml

Would be good to update the libs in the official repo

**Comment by fenos** [comment]
We will get the libs updated in the next release! 🎉

**Comment by fenos** [comment]
This is now being resolved
