### ISSUE TITLE
Development `path` is missing when getting signedUrls

### ISSUE THREAD

**Issue by francistogram** [supabase/storage-api#353]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running 
```typescript
const {data} = await supabase.storage
        .from(BUCKET)
        .createSignedUrls(FILE_PATHS);
```

The type of data is 
```
const data: {
    error: string | null;
    path: string | null;
    signedUrl: string;
}[] | null
```

and this is true for production but if running on the development environment the return value doesn't match and is actually

```typescript
{
  error: string | null;
  signedUrl: string;
};
````

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup a development database with storage
2. Run ```typescript
const {data} = await supabase.storage
        .from(BUCKET)
        .createSignedUrls(FILE_PATHS);
```
3. Notice that while the typescript type is correct the return value is missing `path`

## Expected behavior

Either modify the type to not include `path` or ideally add `path` to the return value


## System information

- OS: macOS
- Version of supabase-js: v2.24.0
- Version of Node.js: v18.9.0

**Comment by Unkn0wn0x** [comment]
Funny, I was also just about to open an issue as I upgraded my selfhosted version of supabase-storage to the latest available, v0.41.2.

The difference in my code is, that I'm calling the API directly as documented here:
* https://supabase.com/docs/reference/self-hosting-storage/generate-presigned-urls-to-retrieve-objects

**Comment by francistogram** [comment]
What version were you on before?

Might be helpful to have some lower bound for when it did work

**Comment by Unkn0wn0x** [comment]
I was on version `v0.29.1` but did not tested all versions between to check when it broke. I tested `v0.40.4` and `v0.41.0`.

**Comment by fenos** [comment]
Hi, thanks for the bug report - I'll have a look and file a patch ASAP

**Comment by Unkn0wn0x** [comment]
Works for me, thanks for the fix!
