### ISSUE TITLE
Custom Postgres roles no longer work in storage.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/storage-api#369]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I created a custom Postgres role for testing awhile back.  The custom role is in stored in the auth.users role column for a particular user.  The role is granted authenticated role privileges.  This used to work on non-upgraded by request storage.  In testing today as another user is encountering custom roles not working in storage.  I now can't access storage with the custom role.

https://supabase.com/docs/guides/auth/row-level-security#using-joins

I'm 95% sure this worked a few weeks ago.  I have files created by this default test role in storage and I believe the change in role was done before those files were uploaded.  I recall specifically worrying about storage working and testing it.

## To Reproduce

Create a custom Postgres role per the Supabase instructions in docs.
do `GRANT authenticated TO customrole;`  (This used to allow storage to work).
Set the auth.users role column for a user to the new role.
Upload a file.
Get error.

## Expected behavior

Custom Postgres roles work in storage.

## System information

Latest Supabase-js
Have NOT requested upgrade to newest storage from support.

## Additional context

Confirming I've used this role before the last file upload by the user that has not been deleted by other testing...
![image](https://github.com/supabase/storage-api/assets/54564956/41374fac-f9fd-43bb-a9b4-7eaace27f279)
![image](https://github.com/supabase/storage-api/assets/54564956/f73cdc05-1554-43d0-b986-6af514b0a520)

**Comment by cipinistor** [comment]
I have the same issue, already described on Discord.

I can confirm that about a week ago this was working and now it doesn't work anymore.
However, becayse the code using the Storage API is recent I thought I might have done something to break it although I really changed nothing related.

This is the description posted on Discord.

While trying to list the content of a bucket I can see this error in the "supabase_db_supabase-local" container (local development):
```
supabase_storage_admin@postgres ERROR:  permission denied to set role "customrole"
supabase_storage_admin@postgres STATEMENT:
      SELECT
        set_config('role', $1, true),
        set_config('request.jwt.claim.role', $2, true),
        set_config('request.jwt', $3, true),
        set_config('request.jwt.claim.sub', $4, true),
        set_config('request.jwt.claims', $5, true),
        set_config('request.headers', $6, true),
        set_config('request.method', $7, true),
        set_config('request.path', $8, true);
```

If I use a JWT with {"role": "authenticated"}, it works perfectly fine.
So it must be a missing role permission.

What I did:
SQL: CREATE ROLE customrole WITH NOLOGIN;
SQL: GRANT customrole TO authenticator;
SQL: GRANT authenticated TO customrole;
Node: generate a JWT with my secret key and {role: "customrole"}
UI: create bucket "test-bucket" with all actions allowed through RLS policies

What I tried (but failed):
SQL: GRANT customrole to supabase_storage_admin;
ERROR:  "supabase_storage_admin" is a reserved role, only superusers can modify it

I can test the API directly by doing a POST request to this URL with the Bearer JWT token and body: {"limit":100,"offset":0,"prefix":""}
http://localhost:54321/storage/v1/object/list/test-bucket
Response:
```
"statusCode": "403",
"error": "Unauthorized",
"message": "new row violates row-level security policy"
```

Again, if I use a JWT with {"role": "authenticated"}, it works perfectly fine.

**Comment by fenos** [comment]
Hi @GaryAustin1 @cipinistor 

We are aware of this.
The reason that this is happening is that we have transitioned the Database Layer from PostgREST to plain Postgres, for portability and performance

Because of this change storage-api is now using `supabase_storage_admin` user to connect to the database, however this user don't have the right grants to impersonate custom roles (just yet). We are working on bringing these grats changes to the `supabase_storage_admin` in the supabase/postgres image soon.

If you are self-hosting storage the way you can fix this is to run amend the grants of the role `supabase_storage_admin` with the following SQL:

```sql
-- Fix permissions for supabase_storage_admin
grant authenticator to supabase_storage_admin;
revoke anon, authenticated, service_role from supabase_storage_admin;
```

Once that is done, you can amend your custom roles or create news ones as following:

```sql
grant custom_role to authenticator;
grant anon to custom_role;
```

Hope this help with having your custom roles working again with the latest version

**Comment by cipinistor** [comment]
Unfortunately we are not self-hosting so this doesn't help.
Except in local development, but not even there because the `supautils` extension makes the roles (supabase_storage_admin, authenticator, etc) protected so the GRANT fails with:
> _role_name_ is a reserved role, only superusers can modify it

Btw, in UI (Database -> Extensions) `supautils` extension says it's not active by default, but it is.

**Comment by timlgl** [comment]
We are experiencing the same problem, and also not able to run the fixes. 
I tried to find the default password for root to have a temporary solution for development, but `your-super-secret-and-long-postgres-password` (from [here](https://supabase.com/docs/guides/self-hosting/docker)) doesn't seem to work on the local dev database.

What's the timeline for the fix here, especially for local development?

**Comment by brandonbrown5** [comment]
@fenos Do you know when this issue will be resolved?

**Comment by fenos** [comment]
Hello guys, we are planning to roll out the change in max 2 weeks' time, for development earlier than this

**Comment by fenos** [comment]
This is now being rolled out!

**Comment by timlgl** [comment]
@fenos which CLI version can I expect this to be shipped with? Current Pre-Release (1.111.1) still doesn't support this. Or are there other steps I have to follow now?

**Comment by psteinroe** [comment]
@sweatybridge when will this fix be on the cli?

**Comment by sweatybridge** [comment]
@psteinroe good call. I will push an update https://github.com/supabase/cli/pull/1747
