### ISSUE TITLE
Storage PUT returning an error

### ISSUE THREAD

**Issue by creativiii** [supabase/storage-api#40]
# Bug report

## Describe the bug

The PUT method used for updating storage files is failing with a cryptic error:

```
node[9379]: ../src/node_http_parser.cc:567:static void node::{anonymous}::Parser::Initialize(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[3]->IsInt32()' failed.
 1: 0xb200e0 node::Abort() [node]
 2: 0xb2015e  [node]
 3: 0xb377b2  [node]
 4: 0xd6fc5b  [node]
 5: 0xd7110c  [node]
 6: 0xd71786 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
 7: 0x1640939  [node]
Aborted
```

## To Reproduce

```
  const arrayBuffer = new ArrayBuffer(8);
  let buffer = Buffer.from(arrayBuffer);

        fetch(
          `${SUPABASE_URL}/storage/v1/object/${projectRef}/avatars/${name}`,
          {
            method: 'PUT',
            mode: 'cors',
            cache: 'no-cache',
            headers: {
              Accept: '*/*',
              Authorization: `Bearer ${SUPABASE_SERVICE}`,
            },
            body: buffer,
          },
        )
          .then((res) => res.json())
          .then((res) => {
            console.log(res);
          });
````

The above code works perfectly with the `POST` method so I assume it's not something wrong with my code? Swagger mentions needing a project's `projectRef`, I assume that's the random string I can find in my url when viewing a project on Supabase? 

## Expected behavior

My file should be updated.

## System information

- OS: Linux
- Version of supabase-js: N/A
- Version of Node.js: 16.4.0

**Comment by inian** [comment]
I will look into this closer tomorrow @creativiii but for now can you try sending the `Content-Type` and `Content-Length` header?

**Comment by creativiii** [comment]
> Wow that does look like a scary error. 
> 
> Does your Node script which is making the request crashing? That is weird
> 
> I will look into this closer tomorrow @creativiii but for now can you try sending the `Content-Type` and `Content-Length` header? 

Thank you for the quick reply! Node isn't crashing, I've tried both `Content-Type` and `Content-Length` but the error stayed the same.

Let me know if you figure out anything or need more info!

**Comment by inian** [comment]
Hi @creativiii, have not been able to reproduce this error with node v16.3. Does running your Node script you provided result in the crash? Which node version are you using?

**Comment by creativiii** [comment]
> Hi @creativiii, have not been able to reproduce this error with node v16.3. Does running your Node script you provided result in the crash? Which node version are you using?

I had tested this on Node 12 and 14 and I was getting the error. I haven't looked at the code since posting this issue but trying it now on both Node 12, 14 and 16 I'm not getting the error anymore.

Did you guys fix something on your end? Oh well 😂

**Comment by inian** [comment]
Oh not sure..We didn't update the storage version in prod in the last 2 weeks, but glad to know it is fixed! Will close the issue for now then.
