### ISSUE TITLE
Asset optimization

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/storage-api#47]
# Feature request
Add an ability to compress Image, Audio and Video in optimizable size.
Similar to: https://firebase.google.com/products/extensions/storage-resize-images

**Comment by bdthombre** [comment]
Surely for the bigger projects this will be helpful

**Comment by vbylen** [comment]
auto asset optimization would be a killer feature

**Comment by inian** [comment]
We have Webp optimizations, resizing and quality transformations. Vote on this discussion [here](https://github.com/orgs/supabase/discussions/10918) if you would like to see more.
