### ISSUE TITLE
Use http.Agent to speed up S3 calls

### ISSUE THREAD

**Issue by inian** [supabase/storage-api#5]
A http agent can be used to keep a set of connections open to S3. By default, a new connection is created each time S3 is accessed which is not ideal. 

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html

**Comment by logikaljay** [comment]
@inian It appears as if `keepAlive: true` is the default in the NodeHttpHandler that the s3-client uses:

https://github.com/aws/aws-sdk-js-v3/blob/49e2d61c809d20ae444d49c7f6c4e997da7cca74/packages/node-http-handler/src/node-http-handler.ts#L44
