### ISSUE TITLE
Handle If-Modified-Since or If-None-match

### ISSUE THREAD

**Issue by inian** [supabase/storage-api#60]
Right now we send cache-control with a max-age header. This is enough if there is a CDN in front of our API which take care of handling 304s if the object hasn't changed. 

But since we don't have a CDN yet, we need to implement this logic ourselves. The fix should be pretty simple - just pass the If-Modified-Since or If-None-match headers from the request on to S3. S3 Should send back a 304 based on that which we can stream on to the client.

**Comment by thebengeu** [comment]
To clarify, this is for `/public/:bucketName/*` and `/sign/:bucketName/*`, where the browser could handle the If-Modified-Since or If-None-match headers, but not `/authenticated/:bucketName/*` and `/:bucketName/*`, where we'd be handling the headers ourselves?

**Comment by thebengeu** [comment]
Decided to handle If-Modified-Since or If-None-match headers for `/authenticated/:bucketName/*` and `/:bucketName/*` too for consistency.
