### ISSUE TITLE
Last modified timestamp will not update after update

### ISSUE THREAD

**Issue by mblog** [supabase/storage-api#67]
# Bug report

## Describe the bug

A replacment of a file with upload (upsert: true) or update will not update the last modified timestamp. The file itself has been updated.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
const avatarFile = event.target.files[0]
const { data, error } = await supabase
  .storage
  .from('avatars')
  .update('public/avatar1.png', avatarFile, {
    cacheControl: 3600,
    upsert: false
  })
```

## Expected behavior

A replacement of a file should update the timestamp.

## System information

supabase-js 1.22.0

**Comment by bruceharrison1984** [comment]
I ran into this today as well with `1.29.0`
