### ISSUE TITLE
add tus - open protocol for resumable uploads

### ISSUE THREAD

**Issue by wiemann** [supabase/storage-api#80]
In order to successfully upload large files, resuming paused/interrupted uploads is usually a requirement.

Do you plan on supporting something like tus ? https://tus.io/

**Comment by millette** [comment]
Should be possible with <https://github.com/tus/tus-node-server> and <https://github.com/fastify/middie>.

**Comment by mashpie** [comment]
…been investigating a fastify implementation.

ended up with something like https://github.com/tus/tus-node-server/issues/241

**Comment by fenos** [comment]
This has now been implemented in v0.35.0
