### ISSUE TITLE
Add support for search in bucket

### ISSUE THREAD

**Issue by joshenlim** [supabase/storage-api#88]
# Feature request

Relevant PR: https://github.com/supabase/supabase/pull/4961

Searching for storage in the dashboard at the moment is a client side search - we do a name string search against what was already fetched from the API

As we're looking to introduce infinite scrolling to the dashboard, this means that we won't (be attempting to) pull all of the folder contents when the user clicks on a folder, hence we need to shift the search logic to the API level

Searching should also support pagination as well (we can just stick with offset limit as per the list items API)

**Comment by alaister** [comment]
Solved in #127
